---
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    component: gateway
  name: gateway-external
  namespace: openfaas
spec:
  loadBalancerIP: ${OPENFAAS_PORTAL_PUBLIC_IP}
  type: LoadBalancer
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 8080
  selector:
    app: gateway
