---
apiVersion: v1
kind: Secret
metadata:
  name: build-bot-dockerhub-secret
  namespace: mico-build-bot
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: ${DOCKERHUB_USERNAME_BASE64}
  password: ${DOCKERHUB_PASSWORD_BASE64}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot-dockerhub
  namespace: mico-build-bot
secrets:
  - name: build-bot-dockerhub-secret
