---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mico-core
  namespace: mico-system
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATA_NEO4J_URI: bolt://neo4j.mico-system:7687
  KUBERNETES_PROMETHEUS_URI: http://prometheus.monitoring:9090/api/v1/query
  SPRING_REDIS_HOST: redis.mico-system
  SPRING_REDIS_PORT: '6379'
---
apiVersion: v1
kind: Service
metadata:
  name: mico-core
  namespace: mico-system
  labels:
    run: mico-core
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    run: mico-core
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mico-core
  namespace: mico-system
spec:
  selector:
    matchLabels:
      run: mico-core
  replicas: 1
  template:
    metadata:
      namespace: mico-system
      labels:
        run: mico-core
    spec:
      containers:
        - name: mico-core
          image: ustmico/mico-core
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: mico-core
          ports:
            - containerPort: 8080
