---
apiVersion: v1
kind: Namespace
metadata:
  name: mico-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: mico-workspace
---
apiVersion: v1
kind: Namespace
metadata:
  name: mico-build-bot
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas
  labels:
    role: openfaas-system
    access: openfaas-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas-fn
  labels:
    role: openfaas-fn

