---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
spec:
  clusterIP: None
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus

